export const PRIMARY_BACKGROUND = '#FFFFFF';
export const PRIMARY_GREEN = '#15AB94';
export const SECONDARY_GREEN = '#A8D6CC';
export const THIRD_GREEN = '#CEEFEA';
export const ERROR_COLOR = '#E33E21';

export const TAG_COLORS = {
  ORANGE_BACKGROUND: '#FFEED6',
  ORANGE_ACCENT: '#D87330',
  YELLOW_BACKGROUND: '#FFFAB8',
  YELLOW_ACCENT: '#9E6C00',
  GREEN_BACKGROUND: '#DEF7F9',
  GREEN_ACCENT: '#0F7C98',
  BLUE_BACKGROUND: '#EDF2FE',
  BLUE_ACCENT: '#3758C7',
  PINK_BACKGROUND: '#FFE9F0',
  PINK_ACCENT: '#CA1A61',
};

export const PROGRESS_BAR_PRIMARY_COLOR = '#5CCBB8';
